language: node_js
node_js:
- iojs
deploy:
  provider: heroku
  api_key:
    secure: b3t8SsDnHRpofJYubR5GUVlHvYSNeGwIb9BIWd+5zGWZIUKpEzI4bLYEvGxZjalFWjBknSrSN+aYp7H29MVLYFDnWmMtBPRbjEgEBEsEm9KcsNoaijhi8JgAuacTQ2Y9Amv7OLRIA1JKHNpf89VYUTYldxKuvl7hsX0O8KHob1RGSp5VD0xUfT/vyDfNilu1qWg00LlFcUwkY55lum//5notqT8dPBBaaHkLIsnLLVy8lv0eGpIW8wxPWGxcxhNp3WGR55uiNZgBAM7/kxDTiAYTtGtaE5MRk2S9RDm7HRJ58mfUF/MjGW/Il2InaDaRDjQXigEXIu26yCGRNWs+xfvkw4DPUgm0AGebyPLXS5/bS9yfkvWtrbFVOJ+n4VIhe4Vtk/9uroBmJxwrl87R+ywAnPglGlfnPZ+bXV0AHoRdHxMynSzRch9cvk0KAreK72O1RPzD+lUtM5atNOEbczLSthF+ij30k6ppncMLrJZ3ggJlDRpV9VPtFu1OQsBwE2yteiwqgg/0dZG716K6NNHQjl3Yg9GKts8b7UNFvAhjtBLdmqBEjCXen4fcL4xZGb1leV1Ukx23aX2d+T43m7fQ00SPinxq9xhybDLDk8yl1ZKOWADetIGHRdcLOI4GS50K63BwJD2kQTCGQLOeATJ6qvCHNzpGALrTX3eIwR0=
  app: crispy-engine
  on:
    repo: yarmatr/crispy-engine
