language: node_js
node_js:
- iojs
deploy:
  provider: heroku
  api_key:
    secure: nYD1FQZsp2rAFFN7vlwbSx1cTIs55D6jNyTlRM89/qJVTHH6H/hzqm/ryY/kb9XEmdqoo/HW9SzISfbQMOrRp386dcPyGgiHAzj7UoX/MpydVlpZ2/NqaSXmBoqZpqInP0cj7w/UnBKIBQDb3Vt7Dg/z0OT2G/Q5zJ2X2hV5Aa/qIB7z65lzMSU/GnKhrNYk4ZP1CVCeAYmfovDEWhTEY4OsJxRjRkD27abam54mwyiFFzbcwUXxG0aqfA6ZbTLTaf80nLztbdOXItfX52i2kVeh04oggRz+f+Xs5BFf/TCAcm2IZPb1bWN/tSM3OWNNQypnFliL8EaiA/k9JfWozD3tR1fO1KO24cM/CxWc8nfTX/9FR2hFC/Vay6vFuZduIDuyfPmxIieWCAM3dGOz0G6XhZXDK6ht2qxZFgdLT6IOdUtZnQGCTr9YIl08yYNAY7vMk+X9pcSNq954s8RDqUsQAxx/KcGNiSxBur25thG/OjEu/MG+MWz1KXJXT757rnqivx/2g5C28PTiMezWizz+n98fX03GMo2qBiNg+z3iTUrlRrWW9XJM56l1T0aTq55IZHRJEz1eJ3VWYktUSFkf5njbpcZ6rlYCRUR7hkx/oFpmj2a+OyRbkW21Wmc8XTmzIhLmXqGAJVs5CqPECp6uCPJ1gOusOgEpwwy1FYw=
